### ISSUE TITLE
How Should I Try it?

### ISSUE THREAD

**Issue by ghost** [AliRn76/HiCoffee-App#5]
### How Should I Try it?
I Don't see any APK file in the Repository  
That I can use it to install this on an Android Device.
**Isn't it an Android app?**

**Comment by AliRn76** [comment]
Hi
Yes It's android app, https://github.com/AliRn76/HiCoffee-App/releases/tag/v1.16.1

**Comment by ghost** [comment]
> Hi
> Yes It's android app, https://github.com/AliRn76/HiCoffee-App/releases/tag/v1.16.1

ありがとう

**Comment by AliRn76** [comment]
どういたしまして

**Comment by AliRn76** [comment]
> > Hi
> > Yes It's android app, https://github.com/AliRn76/HiCoffee-App/releases/tag/v1.16.1
> 
> ありがとう

どういたしまして
